### ISSUE TITLE
Restore purchase documentation page only mentions refreshing the receipt

### ISSUE THREAD

**Issue by jpmhouston** [space-code/flare#55]
I thought restoring purchases was something different. I think I saw a call to `restoreCompletedTransactions()` searching the code but I don't see it exposed in the top-most API.

If refreshing the receipt should be part of restoring purchases, I'd hope that a wrapper framework like this one would just take care of that internally.

If refreshing the receipt is part of some other workflow for an app, I'd hope it were documented from that perspective.

**Comment by nik3212** [comment]
Hi, yes, it seems I forgot to implement this functionality for StoreKit 1. For StoreKit 2, Flare has a restore method that, according to the documentation, is optional.

Anyway, I’ve created a PR that adds receipt refreshing with updated transactions for StoreKit 1. You can use the `receipt(updateTransactions: true)` method, which forces the retrieval of transactions first. If you want to implement your own custom logic for retrieving previous transactions, you can use the `restore` method, which simply calls `restoreCompletedTransactions` under the hood.

I hope to merge these changes today.
