### ISSUE TITLE
Update `Transaction` Model

### ISSUE THREAD

**Issue by nik3212** [space-code/flare#75]
This issue is meant to be a good first issue to get into coding, and into open source contribution over all, as it will require to touch few existing files, is a small change and is documented extensively. If you are new to coding, I encourage you to try this issue. 

Please read our [contribution guidelines](https://github.com/space-code/flare/blob/dev/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

**Feature description**
Update `Transaction` model by adding the new fields `price` and `currency` according to the documentation. 

[Documentation](https://developer.apple.com/documentation/storekit/transaction/transaction_properties).

**Describe the solution you'd like**
Extend the `IStoreTransaction` protocol by adding the new fields and update dependent models.

**Comment by Sauhard74** [comment]
can i work on this issue?
i am getting started with swift as a new language I would love to understand and solve this issue

**Comment by nik3212** [comment]
@Sauhard74, sure ;) I've assigned this issue to you. If you have any questions, let me know

**Comment by nik3212** [comment]
@Sauhard74 how's it going? Do you want to continue on this?

**Comment by nik3212** [comment]
@M7md-Ebrahim, hi! You need to update the models according to the documentation and then update the `StoreTransaction`, `SK1StoreTransaction`, and `SK2StoreTransaction` models. If these fields are not available in StoreKit 1, simply return nil values.

**Comment by nik3212** [comment]
@M7md-Ebrahim, I've assigned this issue to you. If you have any questions, let me know ;)
