### ISSUE TITLE
Update `RenewalInfo` Model

### ISSUE THREAD

**Issue by nik3212** [space-code/flare#76]
This issue is meant to be a good first issue to get into coding, and into open source contribution over all, as it will require to touch few existing files, is a small change and is documented extensively. If you are new to coding, I encourage you to try this issue. 

Please read our [contribution guidelines](https://github.com/space-code/flare/blob/dev/CONTRIBUTING.md) before picking this up, it will also lead you through the process of setting up the repository.

**Feature description**
Update `RenewalInfo ` model by adding the new fields `currency` and `renewalPrice` according to the documentation. 

[Documentation](https://developer.apple.com/documentation/storekit/product/subscriptioninfo/renewalinfo).

**Describe the solution you'd like**
Extend the `IRenewalInfo` protocol by adding the new fields and update dependent models.

**Comment by nik3212** [comment]
@M7md-Ebrahim, did you also want to take on this issue?

**Comment by M7md-Ebrahim** [comment]
Yes, I’m on board! Please go ahead and assign it to me.
